<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-09-01T22:19:17 EDT" name="Suite" finished-at="2023-09-01T22:19:17 EDT" duration-ms="46">
    <groups>
    </groups>
    <test started-at="2023-09-01T22:19:17 EDT" name="Test" finished-at="2023-09-01T22:19:17 EDT" duration-ms="46">
      <class name="seleniumJava.seleniumTest">
        <test-method signature="seleniumBrowse()[pri:0, instance:seleniumJava.seleniumTest@555e0a]" started-at="2023-09-01T22:19:17 EDT" name="seleniumBrowse" finished-at="2023-09-01T22:19:17 EDT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- seleniumBrowse -->
        <test-method signature="seleniumElement()[pri:0, instance:seleniumJava.seleniumTest@555e0a]" started-at="2023-09-01T22:19:17 EDT" name="seleniumElement" finished-at="2023-09-01T22:19:17 EDT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- seleniumElement -->
      </class> <!-- seleniumJava.seleniumTest -->
      <class name="seleniumJava.Intended_to_FailTest">
        <test-method signature="intendedtoFailone()[pri:0, instance:seleniumJava.Intended_to_FailTest@1b33f74]" started-at="2023-09-01T22:19:17 EDT" name="intendedtoFailone" finished-at="2023-09-01T22:19:17 EDT" duration-ms="6" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertFalse(Assert.java:79)
at org.testng.Assert.assertFalse(Assert.java:89)
at seleniumJava.Intended_to_FailTest.intendedtoFailone(Intended_to_FailTest.java:20)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intendedtoFailone -->
      </class> <!-- seleniumJava.Intended_to_FailTest -->
      <class name="seleniumJava.appiumTest">
        <test-method signature="appiumIosApp()[pri:0, instance:seleniumJava.appiumTest@114a4c0]" started-at="2023-09-01T22:19:17 EDT" name="appiumIosApp" finished-at="2023-09-01T22:19:17 EDT" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- appiumIosApp -->
        <test-method signature="appiumNativeApp()[pri:0, instance:seleniumJava.appiumTest@114a4c0]" started-at="2023-09-01T22:19:17 EDT" name="appiumNativeApp" finished-at="2023-09-01T22:19:17 EDT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- appiumNativeApp -->
      </class> <!-- seleniumJava.appiumTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
